### ISSUE TITLE
can I communicate with ur Email？

### ISSUE THREAD

**Issue by LaiGarJing** [Woshiwzl1997/ComNet-OFDM#1]
I have some question with your code， can we chat with Email or wechat？ 
I hope we can have a deep talk !!
And I have some bug when using your code to conduct the signal detection simulation!

**Comment by Woshiwzl1997** [comment]
This is my emil：295495975@qq.com

**Comment by LaiGarJing** [comment]
Can i cheat with ur QQ, and of course ,if u wish , we can talk in chinese because&nbsp; i am chinese




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "woshiwzl"<notifications@github.com&gt;; 
发送时间: 2020年11月8日(星期天) 晚上8:45
收件人: "Woshiwzl1997/ComNet-OFDM"<ComNet-OFDM@noreply.github.com&gt;; 
抄送: "黎嘉盈"<610251857@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Woshiwzl1997/ComNet-OFDM] can I communicate with ur Email？ (#1)





 
This is my emil：295495975@qq.com

**Comment by Woshiwzl1997** [comment]
好的这个就是我qq




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Woshiwzl1997/ComNet-OFDM"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 晚上8:47
收件人:&nbsp;"Woshiwzl1997/ComNet-OFDM"<ComNet-OFDM@noreply.github.com&gt;;
抄送:&nbsp;"ZelinWang@qq.com"<295495975@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Woshiwzl1997/ComNet-OFDM] can I communicate with ur Email？ (#1)





 Can i cheat with ur QQ, and of course ,if u wish , we can talk in chinese because&amp;nbsp; i am chinese 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "woshiwzl"<notifications@github.com&amp;gt;;  
 发送时间: 2020年11月8日(星期天) 晚上8:45 
 收件人: "Woshiwzl1997/ComNet-OFDM"<ComNet-OFDM@noreply.github.com&amp;gt;;  
 抄送: "黎嘉盈"<610251857@qq.com&amp;gt;; "Author"<author@noreply.github.com&amp;gt;;  
 主题: Re: [Woshiwzl1997/ComNet-OFDM] can I communicate with ur Email？ (#1) 
 
 
 
 
 
   
 This is my emil：295495975@qq.com

**Comment by LaiGarJing** [comment]
好的，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Woshiwzl1997/ComNet-OFDM"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月8日(星期天) 晚上8:49
收件人:&nbsp;"Woshiwzl1997/ComNet-OFDM"<ComNet-OFDM@noreply.github.com&gt;;
抄送:&nbsp;"黎嘉盈"<610251857@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Woshiwzl1997/ComNet-OFDM] can I communicate with ur Email？ (#1)





 好的这个就是我qq 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "Woshiwzl1997/ComNet-OFDM"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年11月8日(星期天) 晚上8:47 
 收件人:&amp;nbsp;"Woshiwzl1997/ComNet-OFDM"<ComNet-OFDM@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"ZelinWang@qq.com"<295495975@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [Woshiwzl1997/ComNet-OFDM] can I communicate with ur Email？ (#1) 
 
 
 
 
 
  Can i cheat with ur QQ, and of course ,if u wish , we can talk in chinese because&amp;amp;nbsp; i am chinese  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "woshiwzl"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年11月8日(星期天) 晚上8:45  
  收件人: "Woshiwzl1997/ComNet-OFDM"<ComNet-OFDM@noreply.github.com&amp;amp;gt;;   
  抄送: "黎嘉盈"<610251857@qq.com&amp;amp;gt;; "Author"<author@noreply.github.com&amp;amp;gt;;   
  主题: Re: [Woshiwzl1997/ComNet-OFDM] can I communicate with ur Email？ (#1)  
   
   
   
   
   
     
  This is my emil：295495975@qq.com
